version: "3.3"
services:
  ntm_post:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ntm_post:latest
    container_name: ntm_post
    restart: unless-stopped
    volumes:
      - .:/articles

