services:
  ntm_article:
    build: 
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    image: ntm_article:latest
    container_name: ntm_article
    cpus: 0.75
    mem_reservation: '8gb'
    mem_limit: '8gb'
    init: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - .:/articles

