services:
  articles_pub:
    build: 
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    image: articles_pub:latest
    container_name: articles_pub
    cpus: 0.75
    mem_reservation: '1024M'
    mem_limit: '2048M'
    init: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - .:/articles

