version: "3.9"
services:
  dissertacao:
    build: 
      context: .
      dockerfile: Dockerfile
      shm_size: '1gb'
    image: article_ntm:latest
    container_name: article_ntm
    cpus: 0.75
    mem_reservation: '1024M'
    mem_limit: '2048M'
    init: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - .:/article

